### ISSUE TITLE
might be better an idea to point people to predefined gist search

### ISSUE THREAD

**Issue by johndpope** [JohnSundell/Marathon-Examples#1]
eg.
link straight to url 
https://gist.github.com/search?utf8=%E2%9C%93&q=marathonswift

description: read contents from plist
   
usage:
    marathon run test.swift 

also does this help your project? 
https://github.com/kareman/SwiftShell

**Comment by JohnSundell** [comment]
What's the advantage over the current structure?

**Comment by johndpope** [comment]
you don't have to direct traffic (approve PRs) - developers can simply share snippets of which the github community can curate / upvote / star.

**Comment by johndpope** [comment]
also - it gets the word out there that swift scripting is a thing - so it could compound popularity of this repo. Friends telling friends.

**Comment by JohnSundell** [comment]
I don't see the two things being conflicting though. I still prefer to have an "official" example repo like this for Marathon (the alternative would be to put examples in Marathon's own `README`, which I'd like to avoid for simplicity). But the community are of course super welcome to share examples both here or as Gists (we can even add links to Gists here in this projects `README`).

**Comment by JohnSundell** [comment]
Closing this since there is no action to take 🙂
